// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoJn6t66uNuB2c-TYJZYBreIbyBf3y5lc',
    appId: '1:1005029444215:web:a63801760242840066d472',
    messagingSenderId: '1005029444215',
    projectId: 'travel-buddy-aaef0',
    authDomain: 'travel-buddy-aaef0.firebaseapp.com',
    storageBucket: 'travel-buddy-aaef0.firebasestorage.app',
    measurementId: 'G-XZNZ8RZSR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALUWCgkESbAPPxaN1gD9LxytaRD2uaoNs',
    appId: '1:1005029444215:android:aa59780b4c76d77966d472',
    messagingSenderId: '1005029444215',
    projectId: 'travel-buddy-aaef0',
    storageBucket: 'travel-buddy-aaef0.firebasestorage.app',
  );
}
